Update Pi-AppsTerm
Add help option and check if user gave a mode and app name

diff --git a/files/Pi-AppsTerm b/files/Pi-AppsTerm
--- a/files/Pi-AppsTerm
+++ b/files/Pi-AppsTerm
@@ -8,7 +8,7 @@ LOCAL_VER="$(cat "${workdir}/data/appversion.txt")"
 $1=Mode
 $2=NameOfApp
 Botspot="https://github.com/Botspot/pi-apps"
-InstallLogs="$workdir/installed.txt
+InstallLogs="$workdir/installed.txt"
 
 #Functions
 function error {
@@ -18,51 +18,66 @@ function error {
 
 checkforupdate()
 {
+  #Tells user latest version of Pi-AppsTerm
   echo "latest version: $LATEST_VER"
   echo "local version: $LOCAL_VER"
   #display update dialog if update is available
     if [ $LATEST_VER != $LOCAL_VER ];then
+        #Download Botspots Awesome RPI app store!
         git clone $Botspot
-        wget -O - https://raw.githubusercontent.com/oxmc/pi-apps/master/Pi-AppsTerm | bash
+        #Download latest version of this script
+        wget -O - https://oxmc.github.io/Pi-Apps.info/files/Pi-AppsTerm | bash
       else
          echo "No updates availible"
     fi
 }
 
 #Main
-
-if [ $Mode == "update" ];then
-  checkforupdate
-elif [ $Mode == "install" ];then
-  if [ -d "$workdir/apps/$AppName" ]; then
-    echo "Installing ${AppName}"
-    if [ -f "$workdir/apps/$AppName/install-32" ];then
-      bash $workdir/apps/$AppName/install-32 || error "Unable to install $AppName!"
-    elif [ -f "$workdir/apps/$AppName/install-64" ];then
-      bash $workdir/apps/$AppName/install-64 || error "Unable to install $AppName!"
-    else
-      bash $workdir/apps/$AppName/install || error "Unable to install $AppName!"
-    echo "Installed ${AppName} on ${todaydate}" >> $InstallLogs || error "Unable to log install date for $AppName!"
-    fi
-elif [ $Mode = "uninstall" ];then
-  if [ $AppName == "pi-apps" ];then
-    echo "Are you sure you want to delete pi-apps? y/n"
-    read a
-    if [ $a == "n" ];then
-      echo "Cancelling uninstall..."
-      exit 0
-    else
-      echo "Uninstalling pi-apps..."
-      bash $workdir/uninstall
-      sudo rm /bin/pi-apps || error "Unable to uninstall pi-apps terminal version!"
-    fi
-  fi
-  if [ -d "$workdir/apps/$AppName ];then
-    bash $workdir/apps/$AppName/uninstall || error "Unable to run uninstall script for ${AppName}!"
-  fi
-elif [ $Mode == "version" ];then
-  echo "latest pi-apps version: $LATEST_VER"
-  echo "local pi-apps version: $LOCAL_VER"
+if [ $Mode == "help" ];then
+  echo "To install programs type 'pi-apps install nameofapp', example 'pi-apps install All Is Well' this will install the All Is Well app"    
+  echo "To update pi-apps type 'pi-apps update' this will check if pi-apps is up to date"
+  echo "To uninstall an app type 'pi-apps uninstall nameofapp' this will uninstall the app specified, example 'pi-apps uninstall All Is Well' this will uninstall the All Is Well app"  
+  echo "To check the current version of pi-apps type 'pi-apps version', this will tell you the current verion of pi-apps i.e up to date! new update availible! and out of date! update imedently!"
+  exit 0
+else
+  error "Unkown mode given, for help type 'pi-apps help'"
 fi
-
+if [ $# == "2" ];then
+ if [ $Mode == "update" ];then
+    checkforupdate
+  elif [ $Mode == "install" ];then
+    if [ -d "$workdir/apps/$AppName" ]; then
+      echo "Installing ${AppName}"
+      if [ -f "$workdir/apps/$AppName/install-32" ];then
+        bash $workdir/apps/$AppName/install-32 || error "Unable to install $AppName!"
+      elif [ -f "$workdir/apps/$AppName/install-64" ];then
+        bash $workdir/apps/$AppName/install-64 || error "Unable to install $AppName!"
+      else
+        bash $workdir/apps/$AppName/install || error "Unable to install $AppName!"
+      echo "Installed ${AppName} on ${todaydate}" >> $InstallLogs || error "Unable to log install date for $AppName!"
+      fi
+  elif [ $Mode = "uninstall" ];then
+     if [ $AppName == "pi-apps" ];then
+      echo "Are you sure you want to delete pi-apps? y/n"
+      read a
+      if [ $a == "n" ];then
+        echo "Cancelling uninstall..."
+        exit 0
+      else
+        echo "Uninstalling pi-apps..."
+        bash $workdir/uninstall
+        sudo rm /bin/pi-apps || error "Unable to uninstall pi-apps terminal version!"
+      fi
+    fi
+    if [ -d "$workdir/apps/$AppName" ];then
+      bash $workdir/apps/$AppName/uninstall || error "Unable to run uninstall script for ${AppName}!"
+    fi
+  elif [ $Mode == "version" ];then
+    echo "latest pi-apps version: $LATEST_VER"
+    echo "local pi-apps version: $LOCAL_VER"
+    exit 0
+  fi
+else
+  error "Invalid amounts of arguments recived, please use 'pi-apps <Mode> <AppName>' to use this program correctly, if you need help please type 'pi-apps help'"
+fi
 
