Update Pi-AppsTerm

diff --git a/files/Pi-AppsTerm b/files/Pi-AppsTerm
--- a/files/Pi-AppsTerm
+++ b/files/Pi-AppsTerm
@@ -1,7 +1,7 @@
 #! /bin/bash
 
 #Variables
-workdir="$(readlink -f "$(dirname "$0")")"
+workdir="~/PITM/files/uninstall"
 todaydate="$(date +"%A,%B,%d,%Y")"
 LATEST_VER="$(wget -qO- https://oxmc.github.io/Pi-Apps.info/data/appversion.txt)"
 LOCAL_VER="$(cat "${workdir}/data/appversion.txt")"
@@ -57,8 +57,7 @@ if [ $# == "2" ];then
         exit 0
       else
         echo "Uninstalling pi-apps..."
-        bash $workdir/uninstall
-        sudo rm /bin/pi-apps || error "Unable to uninstall pi-apps terminal version!"
+        bash $workdir/uninstall || error "Unable to run uninstall file!"
       fi
     fi
     if [ -d "$workdir/apps/$AppName" ];then
